//
//  Movie.swift
//  Movies
//
//  Created by Roman Shestopal on 18.10.2023.
//

import Foundation

struct Movies: Codable {
    let page: Int
    let results: [Movie]
    let totalPages, totalResults: Int

    enum CodingKeys: String, CodingKey {
        case page, results
        case totalPages = "total_pages"
        case totalResults = "total_results"
    }
}

// MARK: - ResultElement
struct Movie: Codable {
    let adult: Bool
    let backdropPath: String
    let genreIDS: [Int]
    let id: Int
    let originalLanguage: OriginalLanguage
    let originalTitle, overview: String
    let popularity: Double
    let posterPath, releaseDate, title: String
    let video: Bool
    let voteAverage: Double
    let voteCount: Int

    enum CodingKeys: String, CodingKey {
        case adult
        case backdropPath = "backdrop_path"
        case genreIDS = "genre_ids"
        case id
        case originalLanguage = "original_language"
        case originalTitle = "original_title"
        case overview, popularity
        case posterPath = "poster_path"
        case releaseDate = "release_date"
        case title, video
        case voteAverage = "vote_average"
        case voteCount = "vote_count"
    }
}

enum OriginalLanguage: String, Codable {
    case aa = "aa"
    case af = "af"
    case ak = "ak"
    case an = "an"
    case aas = "as"
    case av = "av"
    case ae = "ae"
    case ay = "ay"
    case az = "az"
    case ba = "ba"
    case bm = "bm"
    case bi = "bi"
    case bo = "bo"
    case br = "br"
    case ca = "ca"
    case cs = "cs"
    case ce = "ce"
    case cu = "cu"
    case cv = "cv"
    case kw = "kw"
    case co = "co"
    case cr = "cr"
    case cy = "cy"
    case da = "da"
    case de = "de"
    case dv = "dv"
    case dz = "dz"
    case eo = "eo"
    case et = "et"
    case eu = "eu"
    case fo = "fo"
    case fj = "fj"
    case fi = "fi"
    case fr = "fr"
    case fy = "fy"
    case ff = "ff"
    case gd = "gd"
    case ga = "ga"
    case gl = "gl"
    case gv = "gv"
    case gn = "gn"
    case gu = "gu"
    case ht = "ht"
    case ha = "ha"
    case sh = "sh"
    case hz = "hz"
    case ho = "ho"
    case hr = "hr"
    case hu = "hu"
    case ig = "ig"
    case io = "io"
    case ii = "ii"
    case iu = "iu"
    case ie = "ie"
    case ia = "ia"
    case id = "id"
    case ik = "ik"
    case iis = "is"
    case it = "it"
    case jv = "jv"
    case ja = "ja"
    case kl = "kl"
    case kn = "kn"
    case ks = "ks"
    case kr = "kr"
    case kk = "kk"
    case km = "km"
    case ki = "ki"
    case rw = "rw"
    case ky = "ky"
    case kv = "kv"
    case kg = "kg"
    case ko = "ko"
    case kj = "kj"
    case ku = "ku"
    case lo = "lo"
    case la = "la"
    case lv = "lv"
    case li = "li"
    case ln = "ln"
    case lt = "lt"
    case lb = "lb"
    case lu = "lu"
    case lg = "lg"
    case mh = "mh"
    case ml = "ml"
    case mr = "mr"
    case mg = "mg"
    case mt = "mt"
    case mo = "mo"
    case mn = "mn"
    case mi = "mi"
    case ms = "ms"
    case my = "my"
    case na = "na"
    case nv = "nv"
    case nr = "nr"
    case nd = "nd"
    case ng = "ng"
    case ne = "ne"
    case nl = "nl"
    case nn = "nn"
    case nb = "nb"
    case no = "no"
    case ny = "ny"
    case oc = "oc"
    case oj = "oj"
    case or = "or"
    case om = "om"
    case os = "os"
    case pi = "pi"
    case pl = "pl"
    case pt = "pt"
    case qu = "qu"
    case rm = "rm"
    case ro = "ro"
    case rn = "rn"
    case ru = "ru"
    case sg = "sg"
    case sa = "sa"
    case si = "si"
    case sk = "sk"
    case sl = "sl"
    case se = "se"
    case sm = "sm"
    case sn = "sn"
    case sd = "sd"
    case so = "so"
    case st = "st"
    case es = "es"
    case sq = "sq"
    case sc = "sc"
    case sr = "sr"
    case ss = "ss"
    case su = "su"
    case sw = "sw"
    case sv = "sv"
    case ty = "ty"
    case ta = "ta"
    case tt = "tt"
    case te = "te"
    case tg = "tg"
    case tl = "tl"
    case th = "th"
    case ti = "ti"
    case to = "to"
    case tn = "tn"
    case ts = "ts"
    case tk = "tk"
    case tr = "tr"
    case tw = "tw"
    case ug = "ug"
    case uk = "uk"
    case ur = "ur"
    case uz = "uz"
    case ve = "ve"
    case vi = "vi"
    case vo = "vo"
    case wa = "wa"
    case wo = "wo"
    case xh = "xh"
    case yi = "yi"
    case za = "za"
    case zu = "zu"
    case ab = "ab"
    case zh = "zh"
    case ps = "ps"
    case am = "am"
    case ar = "ar"
    case bg = "bg"
    case cn = "cn"
    case mk = "mk"
    case el = "el"
    case fa = "fa"
    case he = "he"
    case hi = "hi"
    case hy = "hy"
    case en = "en"
    case ee = "ee"
    case ka = "ka"
    case pa = "pa"
    case bn = "bn"
    case bs = "bs"
    case ch = "ch"
    case be = "be"
}
